CREATE DATABASE IF NOT EXISTS ql_sinhvien
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE ql_sinhvien;

CREATE TABLE IF NOT EXISTS sinhvien (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    hoten VARCHAR(255) NOT NULL,
    masv VARCHAR(50) NOT NULL,
    malop VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_sinhvien_masv (masv)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lophoc (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    malop VARCHAR(50) NOT NULL,
    tenlop VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_lophoc_malop (malop)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
